import localFont from "next/font/local";
import "./globals.css";
import Header from "./_components/header";
import { Amiri } from 'next/font/google';
import Footer from "./_components/footer";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });
const amiri = Amiri({
  weight: '400',
  subsets: ['arabic'],
  display: 'swap',
})
 

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html  className="dark bg-gray-900"  dir="rtl" lang="ar" >
      <body className={`bg-gray-800 ${amiri.className}`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
